---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: public
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dscott@redhat.com
    privateKeySecretRef:
      name: public
    solvers:
      - dns01:
          azureDNS:
            clientID: AZURE_CERT_MANAGER_SP_APP_ID
            clientSecretSecretRef:
              name: azure-dns
              key: client-secret
            subscriptionID: AZURE_SUBSCRIPTION_ID
            tenantID: AZURE_TENANT_ID
            resourceGroupName: AZURE_DNS_ZONE_RESOURCE_GROUP
            hostedZoneName: AZURE_DNS_ZONE
            environment: AzurePublicCloud
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public
  namespace: openshift-ingress
spec:
  secretName: public
  issuerRef:
    name: public
    kind: ClusterIssuer
  commonName: "*.apps.azure.dustinscott.io"
  dnsNames:
    - "*.apps.azure.dustinscott.io"
